export { createLocalSurfaceScope } from './scope.js';
export { createLocalDataBinding } from './local-data.js';
export type {
  CapabilitySourceBinding,
  CapabilitySurfaceBindings,
  CreateCapabilitySurfaceInput,
  CreateDataSurfaceInput,
  CreateLocalSurfaceScopeInput,
  DataServiceCoverage,
  DataServiceSourceBinding,
  DataSurfaceBindings,
  StableOrderField,
  DataSurfaceRequest,
  ExternalOwnership,
  ExternalSurfaceSnapshot,
  ExternalSurfaceStore,
  InternalOwnership,
  LocalSurfaceScope,
  RequestOptions,
  RequestResult,
  SurfaceAddress,
  SurfaceController,
  SurfaceOwnership,
  SurfacePhase,
  SurfaceProposal,
  SurfaceProposalDecision,
  SurfaceReadContext,
  SurfaceRequest,
  SurfaceRevision,
  SurfaceScope,
  SurfaceScopeSnapshot,
  SurfaceSnapshot,
} from './types.js';
export type { CreateLocalDataBindingInput, LocalDataSurfaceBinding } from './local-data.js';
