import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { availablePort } from "../scripts/browser-test-port";
test("additive summary components support keyboard selection, narrow RTL and accessible scope", async ({ page }, testInfo) => {
  const port = await availablePort();
  await page.goto(`/playground/?aeliqoBridgePort=${port}`);
  await page.getByRole("tab", { name: "Documentation", exact: true }).click();
  await page.locator('a[href="#docs-components"]').click();
  const delta = page.getByRole("region", { name: "Standalone Delta example", exact: true });
  await expect(delta.getByText("+11", { exact: true })).toBeVisible();
  const list = page.getByRole("region", { name: "Standalone RecordList example", exact: true });
  const selected = list.getByRole("button", { name: "Small cohort", exact: true });
  await selected.focus(); await page.keyboard.press("Enter");
  await expect(selected).toHaveAttribute("aria-pressed", "true");
  const summary = page.getByRole("region", { name: "Standalone SelectionSummary example", exact: true });
  await summary.getByRole("button", { name: "Clear selection" }).focus();
  await page.keyboard.press("Enter");
  await expect(summary.getByText("No records selected.")).toBeVisible();
  const overview = page.getByRole("region", { name: "Standalone Overview example", exact: true });
  await overview.getByRole("button", { name: "Large cohort", exact: true }).focus();
  await page.keyboard.press("Enter");
  await expect(overview.getByRole("button", { name: "Large cohort", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.setViewportSize({ width: 360, height: 900 });
  await page.emulateMedia({ reducedMotion: "reduce" });
  await overview.locator('.docs-preview').evaluate(element => { element.setAttribute("dir", "rtl"); element.setAttribute("data-aeliqo-theme", "dark"); });
  await overview.screenshot({ path: testInfo.outputPath("additions-overview-narrow-rtl.png") });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const accessibility = await new AxeBuilder({ page }).include('[aria-label="Standalone Delta example"]').include('[aria-label="Standalone RecordList example"]').include('[aria-label="Standalone SelectionSummary example"]').include('[aria-label="Standalone Overview example"]').analyze();
  expect(accessibility.violations).toEqual([]);
});
