import {css, html, nothing} from "lit";
import type {ResultRef, Scalar, VersionRef, VisualizationBindingContext, VisualizationSpec} from "@aeliqo/core";
import {AeliqoCompoundElement, aeliqoCompoundThemeStyles} from "./base.js";
import {stableDataRecordKey} from "../data/shared.js";
import type {
  AeliqoBreakdownGroup, AeliqoComparisonMetric, AeliqoCompoundStatus, AeliqoFormFlowCommitDetail, AeliqoFormFlowStepDetail,
  AeliqoRecordEditorCancelDetail, AeliqoRecordEditorSaveDetail, AeliqoQualityState,
} from "./types.js";
import type {AeliqoDataColumn, AeliqoDataRecord, AeliqoDataScope, AeliqoFieldOption, AeliqoFilterPredicate} from "../data/types.js";
import type {VisualizationDataset} from "../visualization/types.js";
import type {AeliqoFilterChangeDetail, AeliqoSelectionDetail} from "../data/types.js";

const statusValues = ["ready", "loading", "empty", "partial", "stale", "error", "unavailable"] as const;
type Status = typeof statusValues[number];
const status = (value: unknown): Status => typeof value === "string" && (statusValues as readonly string[]).includes(value) ? value as Status : "ready";
const event = <T>(type: string, detail: T, cancelable = true): CustomEvent<T> => new CustomEvent(type, {bubbles: true, composed: true, cancelable, detail: Object.freeze(detail)});

export class AeliqoExplorerElement extends AeliqoCompoundElement {
  static readonly properties = {
    fields: {attribute: false}, predicate: {attribute: false}, rows: {attribute: false}, columns: {attribute: false}, identity: {attribute: false}, entity: {type: String}, selectedKey: {attribute: "selected-key", type: String}, detailRecord: {attribute: false}, detailFields: {attribute: false}, result: {attribute: false}, scope: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, filterLabel: {attribute: "filter-label", type: String}, collectionLabel: {attribute: "collection-label", type: String}, detailLabel: {attribute: "detail-label", type: String}, selection: {type: String},
  };
  static readonly styles = [...aeliqoCompoundThemeStyles, css`[part="panels"] { display: grid; gap: var(--aeliqo-space-24, 1.5rem); grid-template-columns: minmax(12rem, .7fr) minmax(16rem, 1.3fr); } @media (max-width: 48rem) { [part="panels"] { grid-template-columns: 1fr; } }`];
  fields: readonly AeliqoFieldOption[] = []; predicate: AeliqoFilterPredicate | undefined; rows: readonly AeliqoDataRecord[] = []; columns: readonly AeliqoDataColumn[] = []; identity: readonly string[] = []; entity = "record"; selectedKey = ""; detailRecord: AeliqoDataRecord | undefined; detailFields: readonly AeliqoDataColumn[] = []; result: ResultRef | undefined; scope: AeliqoDataScope | undefined; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Explore"; filterLabel = "Filter"; collectionLabel = "Records"; detailLabel = "Selected detail"; selection: "none" | "single" | "multiple" = "single";
  protected override render() {
    const current = status(this.status); const detail = this.detailRecord ?? this.rows.find(row => this.rowKey(row) === this.selectedKey); const statusText = this.statusTemplate(current, this.message);
    return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2>${this.scope ? html`<span part="scope">${this.scopeLabel(this.scope)}</span>` : nothing}</div><div part="panels"><section part="filter" aria-label=${this.filterLabel}><h3>${this.filterLabel}</h3><aeliqo-filter-builder .fields=${this.fields} .predicate=${this.predicate} .entity=${this.entity} .status=${current} @aeliqo-filter-change=${this.forwardFilter}></aeliqo-filter-builder></section><section part="collection" aria-label=${this.collectionLabel}><h3>${this.collectionLabel}</h3><aeliqo-record-list .rows=${this.rows} .columns=${this.columns} .identity=${this.identity} .entity=${this.entity} .selectedKeys=${this.selectedKey ? [this.selectedKey] : []} .result=${this.result} .scope=${this.scope} .selection=${this.selection} .status=${current} @aeliqo-record-list-selection=${this.forwardSelection}></aeliqo-record-list></section><section part="detail" aria-label=${this.detailLabel}><h3>${this.detailLabel}</h3><aeliqo-detail .record=${detail} .fields=${this.detailFields.length ? this.detailFields : this.columns} .identity=${this.identity} .entity=${this.entity} .scope=${this.scope} .status=${current}></aeliqo-detail></section></div>${statusText ? html`<p part="status" role="status">${statusText}</p>` : nothing}</section>`;
  }
  private rowKey(row: AeliqoDataRecord): string | undefined { return stableDataRecordKey(row, this.identity); }
  private readonly forwardFilter = (raw: Event): void => { const detail = (raw as CustomEvent<AeliqoFilterChangeDetail>).detail; if (detail) this.dispatchEvent(event("aeliqo-explorer-filter", detail)); };
  private readonly forwardSelection = (raw: Event): void => { const detail = (raw as CustomEvent<AeliqoSelectionDetail>).detail; if (detail) this.dispatchEvent(event("aeliqo-explorer-selection", detail)); };
}

export class AeliqoComparisonElement extends AeliqoCompoundElement {
  static readonly properties = {compareKeys: {attribute: false}, compareSet: {attribute: false}, metrics: {attribute: false}, entity: {type: String}, status: {type: String}, message: {type: String}, title: {type: String}, result: {attribute: false}, scope: {attribute: false}, identity: {attribute: false}, compatible: {type: Boolean}, selectedKey: {attribute: "selected-key", type: String}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`table { border-collapse: collapse; inline-size: 100%; min-inline-size: 32rem; } [part="table"] { max-inline-size: 100%; overflow-x: auto; } th, td { border-block-end: .0625rem solid var(--aeliqo-color-border, #c9d0d8); padding: var(--aeliqo-space-8, .5rem); text-align: start; vertical-align: top; } th { background: var(--aeliqo-color-surface-muted, #f8fafc); }`];
  compareKeys: readonly string[] = []; compareSet: readonly {readonly key: string; readonly label?: string}[] = []; metrics: readonly AeliqoComparisonMetric[] = []; entity = "record"; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Comparison"; result: ResultRef | undefined; scope: AeliqoDataScope | undefined; identity: readonly string[] = []; compatible = true; selectedKey = "";
  protected override render() { const keys = this.compareKeys.length ? this.compareKeys : this.compareSet.map(item => item.key); const label = (key: string) => this.compareSet.find(item => item.key === key)?.label ?? key; const current = status(this.status); return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2>${this.scope ? html`<span part="scope">${this.scopeLabel(this.scope)}</span>` : nothing}</div>${!this.compatible ? html`<p part="status" role="alert">These metrics cannot be compared because their units or grain are incompatible.</p>` : html`<div part="table" role="region" aria-label="Simultaneous comparison"><table><caption>${this.title}: ${keys.length} ${this.entity}${keys.length === 1 ? "" : "s"}</caption><thead><tr><th scope="col">Metric</th>${keys.map(key => html`<th scope="col"><button part="compare-button" type="button" aria-pressed="true" @click=${() => this.requestCompare(key)}>${label(key)}</button></th>`)}</tr></thead><tbody>${this.metrics.map(metric => html`<tr><th scope="row">${metric.label}${metric.unit ? html` <span part="unit">(${metric.unit})</span>` : nothing}</th>${keys.map(key => html`<td>${metric.values[key] === undefined ? "Not available" : this.display(metric.values[key])}</td>`)}</tr>`)}</tbody></table></div>`}${current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}</section>`; }
  private display(value: Scalar | undefined): string { if (value === undefined || value === null) return "—"; if (typeof value === "object" && !Array.isArray(value) && "decimal" in value) return value.decimal; return String(value); }
  private readonly requestCompare = (key: string): void => {
    const current = this.compareKeys.length ? [...this.compareKeys] : this.compareSet.map(item => item.key);
    const next = current.includes(key) ? current.filter(item => item !== key) : [...current, key];
    if (next.length === 0) return;
    this.dispatchEvent(event("aeliqo-comparison-set", {source: "user", entity: this.entity, keys: next, ...(this.result === undefined ? {} : {result: this.result})}));
  };
}

export class AeliqoBreakdownElement extends AeliqoCompoundElement {
  static readonly properties = {groups: {attribute: false}, rows: {attribute: false}, columns: {attribute: false}, identity: {attribute: false}, entity: {type: String}, groupLabel: {attribute: "group-label", type: String}, metricLabel: {attribute: "metric-label", type: String}, result: {attribute: false}, scope: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, selectedGroup: {attribute: "selected-group", type: String}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`table { border-collapse: collapse; inline-size: 100%; } th, td { border-block-end: .0625rem solid var(--aeliqo-color-border, #c9d0d8); padding: var(--aeliqo-space-8, .5rem); text-align: start; } button { text-align: start; width: 100%; }`];
  groups: readonly AeliqoBreakdownGroup[] = []; rows: readonly AeliqoDataRecord[] = []; columns: readonly AeliqoDataColumn[] = []; identity: readonly string[] = []; entity = "record"; groupLabel = "Group"; metricLabel = "Metric"; result: ResultRef | undefined; scope: AeliqoDataScope | undefined; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Breakdown"; selectedGroup = "";
  protected override render() {
    const current = status(this.status);
    return html`
      <section part="root" data-status=${current} aria-label=${this.title}>
        <div part="header"><h2>${this.title}</h2>${this.scope ? html`<span part="scope">${this.scopeLabel(this.scope)}</span>` : nothing}</div>
        <div part="table"><table><caption>${this.title}: grouped ${this.entity} data</caption><thead><tr><th scope="col">${this.groupLabel}</th><th scope="col">${this.metricLabel}</th><th scope="col">Records</th></tr></thead><tbody>
          ${this.groups.map(group => html`<tr data-selected=${String(group.key === this.selectedGroup)}><th scope="row"><button type="button" aria-pressed=${String(group.key === this.selectedGroup)} @click=${() => this.selectGroup(group.key)}>${group.label}</button></th><td>${this.ratioText(group)}</td><td>${group.recordCount === undefined ? "Not available" : group.recordCount}</td></tr>`)}
        </tbody></table></div>
        ${this.selectedGroup ? html`<section part="detail" aria-label="Contributing records"><h3>Contributing records</h3><aeliqo-record-list .rows=${this.rows} .columns=${this.columns} .identity=${this.identity} .entity=${this.entity} .result=${this.result} .scope=${this.scope} selection="none"></aeliqo-record-list></section>` : nothing}
        ${current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}
      </section>
    `;
  }
  private ratioText(group: AeliqoBreakdownGroup): string { if (group.value !== undefined) return this.scalarText(group.value); if (group.numerator === undefined || group.denominator === undefined) return "Not available"; if (!Number.isFinite(group.numerator) || !Number.isFinite(group.denominator) || group.denominator === 0) return "Not available (zero or invalid denominator)"; return `${(group.numerator / group.denominator * 100).toLocaleString(undefined, {maximumFractionDigits: 2})}%`; }
  private scalarText(value: Scalar): string { if (value === null) return "—"; if (typeof value === "object" && !Array.isArray(value) && "decimal" in value) return value.decimal; return String(value); }
  private readonly selectGroup = (key: string): void => { this.dispatchEvent(event("aeliqo-breakdown-group", {source: "user", key, entity: this.entity, result: this.result})); };
}

export class AeliqoInvestigationElement extends AeliqoCompoundElement {
  static readonly properties = {trendContext: {attribute: false}, trendDatasets: {attribute: false}, eventContext: {attribute: false}, eventDatasets: {attribute: false}, trend: {attribute: false}, baseline: {attribute: false}, events: {attribute: false}, detailRecord: {attribute: false}, detailFields: {attribute: false}, result: {attribute: false}, eventResult: {attribute: false}, identity: {attribute: false}, entity: {type: String}, scope: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, label: {type: String}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`[part="caution"] { border-inline-start: .25rem solid var(--aeliqo-color-warning, #b54708); padding-inline-start: var(--aeliqo-space-12, .75rem); }`];
  trendContext: VisualizationBindingContext = {results: []}; trendDatasets: readonly VisualizationDataset[] = []; eventContext: VisualizationBindingContext = {results: []}; eventDatasets: readonly VisualizationDataset[] = []; trend: VisualizationSpec | undefined; baseline: Scalar | undefined; events: VisualizationSpec | undefined; detailRecord: AeliqoDataRecord | undefined; detailFields: readonly AeliqoDataColumn[] = []; result: ResultRef | undefined; eventResult: ResultRef | undefined; identity: readonly string[] = []; entity = "record"; scope: AeliqoDataScope | undefined; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Investigation"; label = "Trend";
  protected override render() { const current = status(this.status); return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2>${this.scope ? html`<span part="scope">${this.scopeLabel(this.scope)}</span>` : nothing}</div><div part="grid"><section part="trend" aria-label="Trend"><h3>${this.label}</h3>${this.trend ? html`<aeliqo-trend .visualization=${this.trend} .context=${this.trendContext} .datasets=${this.trendDatasets}></aeliqo-trend>` : html`<p part="hint">No trend is available.</p>`}</section><section part="baseline" aria-label="Baseline"><h3>Baseline</h3><aeliqo-metric label="Baseline" .value=${this.baseline}></aeliqo-metric></section><section part="events" aria-label="Event timeline"><h3>Event timeline</h3>${this.events ? html`<aeliqo-timeline .visualization=${this.events} .context=${this.eventContext} .datasets=${this.eventDatasets}></aeliqo-timeline>` : html`<p part="hint">No events are available.</p>`}</section><section part="detail" aria-label="Detail"><h3>Detail</h3><aeliqo-detail .record=${this.detailRecord} .fields=${this.detailFields} .identity=${this.identity} .entity=${this.entity}></aeliqo-detail></section></div><p part="caution">Associations are displayed as evidence in the selected scope. They do not establish causal claims.</p>${current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}</section>`; }
}

export class AeliqoSearchResultsElement extends AeliqoCompoundElement {
  static readonly properties = {detailRecord: {attribute: false}, detailFields: {attribute: false}, query: {type: String}, queryRevision: {attribute: "query-revision", type: String}, resultRevision: {attribute: "result-revision", type: String}, rows: {attribute: false}, columns: {attribute: false}, identity: {attribute: false}, result: {attribute: false}, scope: {attribute: false}, selectedKey: {attribute: "selected-key", type: String}, entity: {type: String}, status: {type: String}, message: {type: String}, title: {type: String}, count: {type: Number}};
  detailRecord: AeliqoDataRecord | undefined; detailFields: readonly AeliqoDataColumn[] = []; query = ""; queryRevision = ""; resultRevision = ""; rows: readonly AeliqoDataRecord[] = []; columns: readonly AeliqoDataColumn[] = []; identity: readonly string[] = []; result: ResultRef | undefined; scope: AeliqoDataScope | undefined; selectedKey = ""; entity = "result"; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Search results"; count: number | undefined;
  protected override render() {
    const stale = this.queryRevision.length > 0 && this.queryRevision !== this.resultRevision;
    const current = stale ? "stale" : status(this.status);
    const total = this.count ?? this.scope?.filteredTotal;
    return html`
      <section part="root" data-status=${current} aria-label=${this.title}>
        <div part="header"><h2>${this.title}</h2><span part="query">${this.query ? `Results for “${this.query}”` : "Enter a search query"}</span></div>
        ${stale ? html`<p part="status" role="status">Results are out of date for this query. Refresh to view them.</p>` : html`
          <p part="scope">${total === undefined ? "Matching count unavailable" : `${total.toLocaleString()} matching results`}</p>
          <aeliqo-card-collection .rows=${this.rows} .columns=${this.columns} .identity=${this.identity} .entity=${this.entity} .selectedKeys=${this.selectedKey ? [this.selectedKey] : []} .result=${this.result} .scope=${this.scope} selection="single" @aeliqo-card-selection=${this.forwardSelection}></aeliqo-card-collection>
          ${this.detailRecord ? html`<aeliqo-detail part="detail" .record=${this.detailRecord} .fields=${this.detailFields.length ? this.detailFields : this.columns} .identity=${this.identity} .entity=${this.entity}></aeliqo-detail>` : nothing}
        `}
      </section>
    `;
  }
  private readonly forwardSelection = (raw: Event): void => { const detail = (raw as CustomEvent<AeliqoSelectionDetail>).detail; if (detail) this.dispatchEvent(event("aeliqo-search-results-selection", detail)); };
}

export class AeliqoRecordEditorElement extends AeliqoCompoundElement {
  static readonly properties = {entity: {type: String}, entityKey: {attribute: "entity-key", type: String}, entityRevision: {attribute: "entity-revision", type: String}, action: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, disabled: {type: Boolean}, invalid: {type: Boolean}, saveLabel: {attribute: "save-label", type: String}, cancelLabel: {attribute: "cancel-label", type: String}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`[part="form"] { display: grid; gap: var(--aeliqo-space-12, .75rem); }`];
  entity = "record"; entityKey = ""; entityRevision = ""; action: VersionRef | undefined; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Edit record"; disabled = false; invalid = false; saveLabel = "Save"; cancelLabel = "Cancel";
  protected override render() { const current = status(this.status); return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2><span part="meta">${this.entity} ${this.entityKey ? `· ${this.entityKey}` : ""}${this.entityRevision ? ` · revision ${this.entityRevision}` : ""}</span></div><aeliqo-form part="form" label=${this.title} ?no-validate=${this.invalid}><slot></slot><div part="actions"><button type="button" ?disabled=${this.disabled} @click=${this.cancel}>${this.cancelLabel}</button><button type="button" ?disabled=${this.disabled || this.invalid} @click=${this.save}>${this.saveLabel}</button></div></aeliqo-form>${this.message || current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}</section>`; }
  private readonly save = (): void => { if (this.disabled || this.invalid || !this.entityKey || !this.entityRevision) return; this.dispatchEvent(event<AeliqoRecordEditorSaveDetail>("aeliqo-record-editor-save", {source: "user", entity: this.entity, key: this.entityKey, entityRevision: this.entityRevision, ...(this.action === undefined ? {} : {action: this.action})})); };
  private readonly cancel = (): void => { if (!this.entityKey || !this.entityRevision) return; this.dispatchEvent(event<AeliqoRecordEditorCancelDetail>("aeliqo-record-editor-cancel", {source: "user", entity: this.entity, key: this.entityKey, entityRevision: this.entityRevision})); };
}

export class AeliqoFormFlowElement extends AeliqoCompoundElement {
  static readonly properties = {steps: {attribute: false}, activeStep: {attribute: "active-step", type: String}, draft: {attribute: false}, validation: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, nextLabel: {attribute: "next-label", type: String}, backLabel: {attribute: "back-label", type: String}, commitLabel: {attribute: "commit-label", type: String}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`[part="step-list"] { display: flex; flex-wrap: wrap; gap: var(--aeliqo-space-8, .5rem); list-style: none; margin: 0 0 var(--aeliqo-space-16, 1rem); padding: 0; } [part="step"][data-active="true"] { font-weight: 700; }`];
  steps: readonly {readonly id: string; readonly label: string}[] = []; activeStep = ""; draft: Readonly<Record<string, Scalar>> = {}; validation: Readonly<Record<string, string | undefined>> = {}; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Form"; nextLabel = "Next"; backLabel = "Back"; commitLabel = "Commit";
  protected override render() { const active = this.activeStep || this.steps[0]?.id || ""; const index = this.steps.findIndex(step => step.id === active); const current = status(this.status); const error = this.validation[active]; return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2><span part="meta">Step ${index < 0 ? 0 : index + 1} of ${this.steps.length}</span></div><ol part="step-list">${this.steps.map(step => html`<li part="step" data-active=${String(step.id === active)}><button type="button" @click=${() => this.moveTo(step.id, step.id === active ? "next" : (this.steps.findIndex(item => item.id === step.id) > index ? "next" : "back"))}>${step.label}</button></li>`)}</ol>${error ? html`<p part="status" role="alert">${error}</p>` : current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}<slot></slot><div part="navigation"><button type="button" ?disabled=${index <= 0} @click=${() => this.moveRelative(-1)}>${this.backLabel}</button>${index >= 0 && index < this.steps.length - 1 ? html`<button type="button" @click=${() => this.moveRelative(1)}>${this.nextLabel}</button>` : html`<button type="button" @click=${this.commit}>${this.commitLabel}</button>`}</div></section>`; }
  private moveRelative(delta: number): void { const active = this.activeStep || this.steps[0]?.id || ""; const index = this.steps.findIndex(step => step.id === active); const target = this.steps[index + delta]; if (target) this.moveTo(target.id, delta > 0 ? "next" : "back"); }
  private moveTo(target: string, direction: "next" | "back"): void { const from = this.activeStep || this.steps[0]?.id || ""; if (!target || target === from) return; if (direction === "next" && this.validation[from]) return; this.dispatchEvent(event<AeliqoFormFlowStepDetail>("aeliqo-form-flow-step", {source: "user", from, to: target, direction})); }
  private readonly commit = (): void => { const active = this.activeStep || this.steps[0]?.id || ""; if (!active || this.validation[active]) return; this.dispatchEvent(event<AeliqoFormFlowCommitDetail>("aeliqo-form-flow-commit", {source: "user", step: active})); };
}

export class AeliqoQualityPanelElement extends AeliqoCompoundElement {
  static readonly properties = {source: {type: String}, freshness: {type: String}, completeness: {type: String}, provenance: {attribute: false}, unsupportedClaims: {attribute: false}, status: {type: String}, message: {type: String}, title: {type: String}, state: {attribute: false}};
  static readonly styles = [...aeliqoCompoundThemeStyles, css`dl { display: grid; gap: var(--aeliqo-space-8, .5rem) var(--aeliqo-space-16, 1rem); grid-template-columns: minmax(8rem, max-content) minmax(0, 1fr); margin: 0; } dt { color: var(--aeliqo-color-muted, #475569); } dd { margin: 0; overflow-wrap: anywhere; } ul { margin-block: var(--aeliqo-space-8, .5rem) 0; padding-inline-start: 1.25rem; }`];
  source = ""; freshness = ""; completeness = ""; provenance: readonly string[] = []; unsupportedClaims: readonly string[] = []; status: AeliqoCompoundStatus = "ready"; message = ""; title = "Data quality"; state: AeliqoQualityState | undefined;
  protected override render() { const source = this.state?.source ?? this.source; const freshness = this.state?.freshness ?? this.freshness; const completeness = this.state?.completeness ?? this.completeness; const provenance = this.state?.provenance ?? this.provenance; const unsupported = this.state?.unsupportedClaims ?? this.unsupportedClaims; const current = status(this.status); return html`<section part="root" data-status=${current} aria-label=${this.title}><div part="header"><h2>${this.title}</h2><span part="meta">${current === "ready" ? "Reported metadata" : this.statusText(current, this.message)}</span></div><dl><dt>Source</dt><dd>${source || "Not supplied"}</dd><dt>Freshness</dt><dd>${freshness || "Not supplied"}</dd><dt>Completeness</dt><dd>${completeness || "Not supplied"}</dd><dt>Provenance</dt><dd>${provenance.length ? html`<ul>${provenance.map(item => html`<li>${item}</li>`)}</ul>` : "Not supplied"}</dd></dl>${current !== "ready" ? html`<p part="status" role="status">${this.statusText(current, this.message)}</p>` : nothing}${unsupported.length ? html`<p part="caution">Unsupported claims are shown explicitly and are not presented as facts.</p><ul part="unsupported">${unsupported.map(item => html`<li>${item}</li>`)}</ul>` : nothing}</section>`; }
}
