import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { createCompanion } from './server.js';
const app=createCompanion();
await app.ready;
await app.mcp.server.connect(new StdioServerTransport());
console.error(`Aeliqo companion: HTTP 127.0.0.1:${app.port}, WS 127.0.0.1:${app.mcp.bridge.port}`);
console.error(`Pair this workspace: http://127.0.0.1:5173/?aeliqoBridgePort=${app.mcp.bridge.port}&aeliqoCompanionPort=${app.port}#aeliqoPairToken=${app.mcp.bridge.pairingToken}`);
let closing=false;
const close=async()=>{if(closing)return;closing=true;await app.close();};
process.on('SIGINT',()=>{void close();});
process.on('SIGTERM',()=>{void close();});
process.stdin.on('end',()=>{void close();});
