import {registerAeliqoElements} from '@aeliqo/web';
import {detectWebMcp} from '@aeliqo/agent/webmcp';
import {AeliqoRegionElement} from '@aeliqo/web/region';
import {AeliqoComparisonElement} from '@aeliqo/web/comparison';
import {AeliqoDetailElement} from '@aeliqo/web/detail';
import {AeliqoTextFieldElement} from '@aeliqo/web/text-field';
import {createDemoEngine,type DemoOutput,type DemoView,type DemoPresentation} from './playground-engine.js';
import type {Outcome,Task} from '@aeliqo/core';
import {syncComponentTheme} from './site.js';

const $=<T extends HTMLElement=HTMLElement>(id:string):T=>{const node=document.getElementById(id);if(!node)throw Error(`Missing playground control ${id}`);return node as T;};
for(const [name,ctor] of [['aeliqo-region',AeliqoRegionElement],['aeliqo-comparison',AeliqoComparisonElement],['aeliqo-detail',AeliqoDetailElement],['aeliqo-text-field',AeliqoTextFieldElement]] as const)if(!customElements.get(name))customElements.define(name,ctor);
registerAeliqoElements();
let presentedLeases:ReturnType<DemoOutput['handle']['retain']>[]=[];
let engine=createDemoEngine();let outputs:readonly DemoOutput[]=[];let presentations:readonly DemoPresentation[]=[];let accepted:Task|undefined;let generation=0;let dirty=false;let productFormDirty=false;
const draft=$<HTMLTextAreaElement>('task-draft');const view=$<HTMLSelectElement>('result-view');const team=$<HTMLSelectElement>('play-team');const dataset=$<HTMLSelectElement>('dataset');const activities:{stage:string;message:string}[]=[];
function activity(stage:string,message:string){activities.push({stage,message});if(activities.length>40)activities.shift();updateInspector();}
function showError(message:string){$('play-error').hidden=false;$('play-error').textContent=message;activity('rejected',message);}
function outcome<T>(result:Outcome<T>):T|undefined{if(!result.ok){showError(result.diagnostics.map(item=>`${item.code}: ${item.message}`).join(' '));return;}return result.value;}
function updateInspector(){const selection=$<HTMLSelectElement>('inspector-tab').value;const value=selection==='Task'?accepted??{status:'No accepted task'}:selection==='Data'?outputs.map(output=>({descriptor:output.descriptor,rows:output.rows})):selection==='Experience'?presentations.map(item=>({experience:item.experience,plan:item.plan})):{budget:engine.budget,events:activities};$('inspector-content').textContent=JSON.stringify(value,null,2);}
function present(next:readonly DemoOutput[],requested:DemoView):boolean{
 const prepared:DemoPresentation[]=[];
 for(const output of next){const checked=outcome(engine.present(output,requested));if(!checked)return false;prepared.push(checked);}
 const nodes=next.map((output,index)=>{const section=document.createElement('section');const heading=document.createElement('h3');heading.textContent=output.descriptor.ref.outputId==='main'?'Evaluated output':output.descriptor.ref.outputId==='first-half'?'3–16 August 2026':output.descriptor.ref.outputId==='second-half'?'17–30 August 2026':output.descriptor.ref.outputId;const region=new AeliqoRegionElement();region.presentation=prepared[index]!.validated;region.results=[{ref:output.descriptor.ref,rows:output.rows,visualizationContext:{results:[output.descriptor],catalog:engine.catalog}}];section.append(heading,region);return section;});
 const nextLeases=next.map(output=>output.handle.retain());$('result-canvas').replaceChildren(...nodes);for(const lease of presentedLeases)lease.release();presentedLeases=nextLeases;outputs=next;presentations=prepared;view.value=requested;void syncComponentTheme($('result-canvas'));return true;
}
async function evaluate(task:unknown,requested:DemoView='table'){
 const token=++generation;$('play-error').hidden=true;$('play-status').textContent='Evaluating…';activity('evaluate','Requested local evaluation.');
 const result=await engine.evaluate(task);if(token!==generation)return;
 const next=outcome(result);if(!next){$('play-status').textContent=outputs.length?'The previous authorized view is retained.':'No result was committed.';return;}
 if(!present(next,requested)){$('play-status').textContent='The previous view is retained; presentation was rejected.';return;}
 accepted=next[0]?.task;const rows=next.reduce((count,output)=>count+output.rows.length,0);$('play-status').textContent=`${next.length} complete output${next.length===1?'':'s'} · ${rows} result rows · Synthetic demo scope.`;$('result-title').textContent=accepted?.goal??'Results';
 if(!dirty)draft.value=JSON.stringify(accepted,null,2);activity('commit',`Presented task revision ${accepted?.revision}.`);
 if(dataset.value==='products')mountCommerce(next[0]);updateInspector();
}
const browse=()=>evaluate(dataset.value==='products'?engine.productTask():engine.peopleTask(team.value));
$('refresh').addEventListener('click',()=>void browse());team.addEventListener('change',()=>void browse());
$('define-meaning').addEventListener('click',()=>{if(!outcome(engine.defineAbsenceMeaning()))return;activity('meaning','Activated built-in sum of supplied absence days, revision 1. No rate or employee-count inference.');$('cohort-status').textContent='Meaning ready. Refresh and freeze an employee collection for a fixed-cohort trend.';void browse();});
$('rank').addEventListener('click',()=>{const task=outcome(engine.rankingTask(team.value));if(task)void evaluate(task,'bar');});
$('freeze').addEventListener('click',async()=>{const selected=outputs[0];if(!selected){showError('Browse an employee collection first.');return;}const fixed=outcome(await engine.freezeCohort(selected,'People frozen from the displayed result'));if(fixed){$('cohort-status').textContent=`Fixed cohort: ${fixed.members} people · source revision ${fixed.source.revision}. Later filters do not change these identities.`;activity('cohort',`Froze ${fixed.members} stable employee identities.`);}});
$('trend').addEventListener('click',()=>{const task=outcome(engine.trendTask());if(task)void evaluate(task,'trend');});
$('compare-periods').addEventListener('click',()=>{const task=outcome(engine.comparisonTask());if(task)void evaluate(task);});
$('inspect-contributor').addEventListener('click',()=>void evaluate(engine.contributorTask($<HTMLSelectElement>('contributor').value)));
view.addEventListener('change',()=>{if(outputs.length){const previous=presentations[0]?.plan.nodes.some(node=>node.representation.id==='visualization.bar')?'bar':presentations[0]?.plan.nodes.some(node=>node.representation.id==='visualization.trend')?'trend':'table';if(!present(outputs,view.value as DemoView))view.value=previous;else{$('play-error').hidden=true;activity('present',`Changed to ${view.value} without a model call.`);}}});
$('cancel').addEventListener('click',()=>{generation++;engine.cancel();$('play-status').textContent='Query cancelled. The current authorized view is retained.';activity('cancel','Cancelled pending evaluation.');});
draft.addEventListener('input',()=>{dirty=true;});
$('evaluate-draft').addEventListener('click',()=>{try{const task:unknown=JSON.parse(draft.value);void evaluate(task);}catch{showError('The task document is not valid JSON. Correct it and evaluate again.');}});
$('export-task').addEventListener('click',()=>{if(!accepted){showError('Evaluate a task before export.');return;}const blob=new Blob([JSON.stringify({version:'1',kind:'aeliqo-demo-task',task:accepted},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='aeliqo-task.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);activity('export','Exported the accepted Task without records or credentials.');});
$('reset').addEventListener('click',()=>{if((dirty||productFormDirty)&&!confirm('Reset the session and discard your local drafts?'))return;generation++;for(const lease of presentedLeases)lease.release();presentedLeases=[];$('result-canvas').replaceChildren();engine.dispose();engine=createDemoEngine();outputs=[];presentations=[];accepted=undefined;dirty=false;productFormDirty=false;draft.value='';$('commerce-form').replaceChildren();$('cohort-status').textContent='No fixed cohort yet.';activity('reset','Started a new ephemeral session.');void browse();});
let lastPanel:string|undefined;
const narrow=matchMedia('(max-width:900px)');
const panels=[['source-toggle','source-panel','source-close'],['inspector-toggle','inspector-panel','inspector-close']] as const;
function panelModality(){if(narrow.matches){const visible=panels.filter(([,panel])=>!$(panel).hidden);if(visible.length>1){const keep=visible.find(([,panel])=>panel===lastPanel)??visible.at(-1)!;for(const [toggle,panel]of visible)if(panel!==keep[1]){$(panel).hidden=true;$(toggle).setAttribute('aria-expanded','false');}$(keep[1]).querySelector<HTMLElement>('textarea,select')?.focus();}}const opened=panels.find(([,panel])=>!$(panel).hidden);const modal=narrow.matches&&opened!==undefined;for(const element of document.querySelectorAll<HTMLElement>('.topbar,footer,.playground-header,.playground-toolbar,.playground-main'))element.inert=modal;for(const [,panel]of panels){$(panel).setAttribute('role',modal&&!$(panel).hidden?'dialog':'complementary');if(modal&&!$(panel).hidden)$(panel).setAttribute('aria-modal','true');else $(panel).removeAttribute('aria-modal');}}
function closePanel(toggle:string,panel:string){$(panel).hidden=true;$(toggle).setAttribute('aria-expanded','false');panelModality();$(toggle).focus();}
for(const [toggle,panel,close] of panels){
 $(toggle).addEventListener('click',()=>{const hidden=!$(panel).hidden;if(!hidden&&narrow.matches)for(const [otherToggle,otherPanel]of panels)if(otherPanel!==panel){$(otherPanel).hidden=true;$(otherToggle).setAttribute('aria-expanded','false');}$(panel).hidden=hidden;if(!hidden)lastPanel=panel;$(toggle).setAttribute('aria-expanded',String(!hidden));panelModality();if(!hidden)$(panel).querySelector<HTMLElement>('textarea,select')?.focus();});
 $(close).addEventListener('click',()=>closePanel(toggle,panel));
 $(panel).addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closePanel(toggle,panel);}else if(event.key==='Tab'&&narrow.matches){const controls=[...$(panel).querySelectorAll<HTMLElement>('button,textarea,select,[tabindex="0"]')].filter(node=>node.getClientRects().length>0);const first=controls[0],last=controls.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}});
}
narrow.addEventListener('change',panelModality);
$('inspector-tab').addEventListener('change',updateInspector);
for(const [id,panel,direction] of [['source-resize','source-panel',1],['inspector-resize','inspector-panel',-1]] as const){const handle=$(id);let initial=320;let start=0;const resize=(width:number)=>{const next=Math.max(260,Math.min(520,width));$(panel).style.setProperty('--panel-width',`${next}px`);handle.setAttribute('aria-valuenow',String(next));};handle.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();resize(Number(handle.getAttribute('aria-valuenow'))+(event.key==='ArrowRight'?16:-16)*direction);}});handle.addEventListener('pointerdown',event=>{initial=Number(handle.getAttribute('aria-valuenow'));start=event.clientX;handle.setPointerCapture(event.pointerId);});handle.addEventListener('pointermove',event=>{if(handle.hasPointerCapture(event.pointerId))resize(initial+(event.clientX-start)*direction);});handle.addEventListener('pointerup',event=>{if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId);});}
function mountCommerce(output:DemoOutput|undefined){
 if(!output)return;const rows=output.rows.filter(row=>typeof row.product_id==='string');const controls=$('commerce-controls');controls.replaceChildren();const selects=[0,1].map(index=>{const label=document.createElement('label');label.textContent=index===0?'First product ':'Second product ';const select=document.createElement('select');select.setAttribute('aria-label',label.textContent.trim());for(const row of rows){const option=document.createElement('option');option.value=String(row.product_id);option.textContent=String(row.name);select.append(option);}select.selectedIndex=Math.min(index,rows.length-1);label.append(select);controls.append(label);return select;});
 function update(){const chosen=selects.map(select=>rows.find(row=>row.product_id===select.value)).filter(row=>row!==undefined);const unique=chosen.filter((row,index)=>chosen.findIndex(item=>item.product_id===row.product_id)===index);const comparison=new AeliqoComparisonElement();comparison.entity='products';comparison.compareSet=unique.map(row=>({key:String(row.product_id),label:String(row.name)}));comparison.compareKeys=unique.map(row=>String(row.product_id));comparison.metrics=[{id:'price',label:'Price',unit:'USD',values:Object.fromEntries(unique.map(row=>[String(row.product_id),typeof row.price==='object'&&row.price!==null&&'decimal' in row.price?String(row.price.decimal):'Unknown']))},{id:'stock',label:'Stock',unit:'items',values:Object.fromEntries(unique.map(row=>[String(row.product_id),Number(row.stock)]))}];comparison.result=output!.descriptor.ref;comparison.scope={kind:'filtered',label:'Selected synthetic products',loaded:unique.length,filteredTotal:unique.length};$('commerce-comparison').replaceChildren(comparison);const detail=new AeliqoDetailElement();detail.record=chosen[0];detail.fields=[{key:'name',label:'Name'},{key:'category',label:'Category'},{key:'price',label:'Price (USD)'},{key:'stock',label:'Stock'}];$('commerce-detail').replaceChildren(detail);void syncComponentTheme($('commerce'));}
 selects.forEach(select=>select.addEventListener('change',update));update();
 if(!$('commerce-form').children.length){const form=document.createElement('form');const name=new AeliqoTextFieldElement();name.name='name';name.label='Your name';name.required=true;const note=new AeliqoTextFieldElement();note.name='note';note.label='Enquiry note';const button=document.createElement('button');button.type='submit';button.textContent='Review local enquiry';const receipt=document.createElement('p');receipt.setAttribute('role','status');form.append(name,note,button,receipt);form.addEventListener('aeliqo-input-change',()=>{productFormDirty=true;});form.addEventListener('submit',event=>{event.preventDefault();if(!form.reportValidity())return;receipt.textContent=`Draft reviewed for ${String(new FormData(form).get('name')??'')}. This remains local; no enquiry was sent.`;productFormDirty=false;});$('commerce-form').append(form);}
}
function syncDatasetVisibility(){const commerce=dataset.value==='products';$('people-actions').hidden=commerce;$('team-control').hidden=commerce;$('cohort-status').hidden=commerce;$('commerce').hidden=!commerce;}
dataset.addEventListener('change',()=>{syncDatasetVisibility();void browse();});
$('webmcp-status').textContent=detectWebMcp().supported?'WebMCP experimental API detected · unpaired':'WebMCP unavailable in this browser';
window.addEventListener('pagehide',event=>{engine.cancel();if(!event.persisted){for(const lease of presentedLeases)lease.release();presentedLeases=[];engine.dispose();}});
syncDatasetVisibility();
void browse();
