import { act, cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { renderToString } from "react-dom/server";
import { hydrateRoot } from "react-dom/client";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createWorkspace, defineDataset, type DataSnapshot } from "@aeliqo/core";
import { Ranking } from "./ranking";
import { Trend } from "./trend";
import { Detail } from "./detail";
import { Filter } from "./filter";
import { Explorer, Workspace } from "./index";

afterEach(cleanup);
const dataset = defineDataset({ id: "balance", label: "Balances", entity: "Account", identity: "id", labelField: "name", dimensions: [{ key: "name", label: "Name" }], metrics: [{ key: "balance", label: "Balance", aggregation: "sum" }], timeFields: [{ key: "day", label: "Day", temporal: "date" }] });
const snapshot: DataSnapshot = { status: "ready", records: [{ id: "a", name: "Debit", balance: -4, day: "2026-01-01" }, { id: "b", name: "Credit", balance: 6, day: "2026-01-02" }, { id: "c", name: "Unknown", balance: null, day: "2026-01-03" }] };

describe("standalone W1 foundation", () => {
  it("shows negatives left of a shared zero baseline and nulls last", () => {
    const onSelect = vi.fn();
    render(<Ranking dataset={dataset} snapshot={snapshot} metric="balance" direction="asc" onSelect={onSelect} />);
    const rows = screen.getAllByRole("listitem");
    expect(rows.map(row => row.textContent)).toEqual([expect.stringContaining("Debit"), expect.stringContaining("Credit"), expect.stringContaining("Unknown")]);
    const negative = rows[0]!.querySelector<HTMLElement>(".aeliqo-bar")!;
    const positive = rows[1]!.querySelector<HTMLElement>(".aeliqo-bar")!;
    expect(negative.style.width).toBe("40%");
    expect(negative.style.marginInlineStart).toBe("0%");
    expect(positive.style.width).toBe("60%");
    expect(positive.style.marginInlineStart).toBe("40%");
    fireEvent.click(within(rows[0]!).getByRole("button"));
    expect(onSelect).toHaveBeenCalledWith("a");
  });
  it("server renders and hydrates all three standalone views with controlled selection", async () => {
    const onSelect = vi.fn();
    const ui = <><Ranking dataset={dataset} snapshot={snapshot} metric="balance" selectedId="b" onSelect={onSelect} /><Trend dataset={dataset} snapshot={snapshot} metric="balance" timeField="day" /><Detail dataset={dataset} snapshot={snapshot} selectedId="b" /></>;
    const container = document.createElement("div");
    container.innerHTML = renderToString(ui);
    document.body.append(container);
    const onRecoverableError = vi.fn();
    let root: ReturnType<typeof hydrateRoot>;
    await act(async () => { root = hydrateRoot(container, ui, { onRecoverableError }); });
    expect(onRecoverableError).not.toHaveBeenCalled();
    const button = within(container).getByRole("button", { name: /Credit/ });
    expect(button.getAttribute("aria-pressed")).toBe("true");
    fireEvent.click(button);
    expect(onSelect).toHaveBeenCalledWith("b");
    expect(within(container).getByRole("heading", { name: "Credit" })).toBeTruthy();
    await act(async () => root!.unmount());
    container.remove();
  });
  it("distinguishes invalid field, empty, loading, error, partial and unavailable selection", () => {
    const view = render(<Ranking dataset={dataset} snapshot={snapshot} metric="missing" />);
    expect(screen.getByRole("alert").textContent).toContain("declared metric");
    view.rerender(<Trend dataset={dataset} snapshot={snapshot} metric="balance" timeField="missing" />);
    expect(screen.getByRole("alert").textContent).toContain("time field");
    view.rerender(<Detail dataset={dataset} snapshot={{ records: [], status: "loading" }} selectedId="a" />);
    expect(screen.getByRole("status").textContent).toContain("Loading");
    view.rerender(<Detail dataset={dataset} snapshot={{ records: [], status: "error", error: "Host denied access" }} selectedId="a" />);
    expect(screen.getByRole("alert").textContent).toContain("Host denied access");
    view.rerender(<Ranking dataset={dataset} snapshot={{ records: [], status: "ready" }} metric="balance" />);
    expect(screen.getByRole("status").textContent).toContain("No records");
    view.rerender(<Detail dataset={dataset} snapshot={{ ...snapshot, scope: "loaded-page", stale: true }} selectedId="gone" />);
    expect(screen.getByText("The selected record is unavailable in this view.")).toBeTruthy();
    expect(screen.getByText("Loaded page only; results are not global.")).toBeTruthy();
    expect(screen.getByText("Data is stale.")).toBeTruthy();
  });
  it("removes only one committed filter without losing a composing draft", () => {
    const onChange = vi.fn();
    const filters = [{ field: "name", operator: "eq" as const, value: "Debit" }, { field: "balance", operator: "gt" as const, value: -10 }];
    const view = render(<Filter dataset={dataset} filters={filters} onChange={onChange} />);
    const input = screen.getByLabelText("Value");
    fireEvent.change(input, { target: { value: "編集" } });
    fireEvent.compositionStart(input);
    fireEvent.click(screen.getByRole("button", { name: "Remove Name filter" }));
    expect(onChange).toHaveBeenLastCalledWith([filters[1]]);
    view.rerender(<Filter dataset={dataset} filters={[filters[1]!]} onChange={onChange} />);
    expect((input as HTMLInputElement).value).toBe("編集");
    fireEvent.submit(input.closest("form")!);
    expect(onChange).toHaveBeenCalledTimes(1);
  });
  it("Explorer uses one scope and preserves Filter draft across collection variants", () => {
    const store = createWorkspace({ dataPort: { listDatasets: () => [dataset], getDataset: () => dataset, getSnapshot: () => snapshot, subscribe: () => () => {} }, nodes: [{ id: "explorer", component: "Explorer", datasetId: dataset.id, metric: "balance" }] });
    render(<Workspace store={store} renderers={{ Explorer }} />);
    const input = screen.getByLabelText("Value");
    fireEvent.change(input, { target: { value: "Debit" } });
    fireEvent.click(screen.getByRole("button", { name: "Apply filter" }));
    fireEvent.click(screen.getByRole("button", { name: "Table" }));
    expect(within(screen.getByRole("table")).queryByText("Credit")).toBeNull();
    fireEvent.click(screen.getByRole("button", { name: "Debit" }));
    expect(screen.getByRole("heading", { name: "Debit" })).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Ranking" }));
    expect((input as HTMLInputElement).value).toBe("Debit");
    expect(screen.getByRole("button", { name: /01 Debit/ }).getAttribute("aria-pressed")).toBe("true");
  });
});
