import {expect,test} from '@playwright/test';
test('real employee tasks, named periods, fixed cohort, view rejection and drafts',async({page})=>{
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/playground/');await expect(page.locator('#play-status')).toContainText('4 result rows');await expect(page.locator('aeliqo-region aeliqo-table')).toBeVisible();await page.getByRole('button',{name:'Rank absence days',exact:true}).click();await expect(page.getByRole('alert')).toContainText('demo.needs-meaning');await expect(page.locator('aeliqo-region')).toBeVisible();await page.getByRole('button',{name:'Define absence days',exact:true}).click();await expect(page.locator('#play-status')).toContainText('4 result rows');await page.locator('#play-team').selectOption('Engineering');await expect(page.locator('#play-status')).toContainText('2 result rows');await page.getByRole('button',{name:'Freeze current people',exact:true}).click();await expect(page.locator('#cohort-status')).toContainText('2 people');await page.getByRole('button',{name:'Trend fixed cohort',exact:true}).click();await expect(page.locator('aeliqo-trend')).toBeVisible();await expect(page.locator('#play-status')).toContainText('4 result rows');await page.getByRole('button',{name:'Compare periods',exact:true}).click();await expect(page.locator('aeliqo-region')).toHaveCount(2);await expect(page.locator('#play-status')).toContainText('2 complete outputs');await page.getByRole('button',{name:'Inspect records',exact:true}).click();await expect(page.locator('#play-status')).toContainText('4 result rows');await page.locator('#result-view').selectOption('bar');await expect(page.getByRole('alert')).toContainText('unsupported-view');await expect(page.locator('aeliqo-region')).toHaveCount(1);
 await page.getByRole('button',{name:'Source',exact:true}).click();await page.locator('#task-draft').fill('{"unfinished":');await page.getByRole('button',{name:'Evaluate task',exact:true}).click();await expect(page.getByRole('alert')).toContainText('not valid JSON');await expect(page.locator('#task-draft')).toHaveValue('{"unfinished":');await page.keyboard.press('Escape');await expect(page.locator('#source-panel')).toBeHidden();await expect(page.locator('#source-toggle')).toBeFocused();await page.getByRole('button',{name:'Source',exact:true}).click();await expect(page.locator('#task-draft')).toHaveValue('{"unfinished":');await page.locator('#source-resize').focus();await page.keyboard.press('ArrowRight');await expect(page.locator('#source-resize')).toHaveAttribute('aria-valuenow','336');await page.screenshot({path:'artifacts/site-browser/playground-desktop.png',fullPage:true});expect(errors).toEqual([]);
});
test('commerce compare, detail and local form remain usable without model access',async({page})=>{const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/playground/');await page.locator('#dataset').selectOption('products');await expect(page.locator('#commerce')).toBeVisible();await expect(page.locator('aeliqo-comparison')).toContainText('Field notebook');await expect(page.locator('aeliqo-detail')).toBeVisible();await page.getByRole('textbox',{name:'Your name',exact:true}).fill('Nino');await page.getByRole('textbox',{name:'Enquiry note',exact:true}).fill('Please compare these.');await page.getByRole('button',{name:'Review local enquiry',exact:true}).click();await expect(page.locator('#commerce-form [role=status]')).toContainText('Draft reviewed for Nino');await page.getByLabel('First product',{exact:true}).selectOption('lamp');await expect(page.getByRole('textbox',{name:'Enquiry note',exact:true})).toHaveValue('Please compare these.');expect(errors).toEqual([]);});
test('home, deep docs, search, theme and narrow playground remain navigable',async({page})=>{const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('/');await page.locator('#team').selectOption('Engineering');await expect(page.locator('#demo-status')).toContainText('2 of 4');await page.locator('#theme').selectOption('dark');await page.goto('/docs/concepts/');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.getByRole('button',{name:'Search docs'}).click();await page.getByRole('searchbox').fill('nonsensezzzzz');await expect(page.locator('aeliqo-dialog')).toContainText('No pages found');await page.getByRole('searchbox').fill('meaning');await expect(page.locator('aeliqo-dialog').getByRole('link').first()).toBeVisible();await page.keyboard.press('Escape');await page.setViewportSize({width:360,height:800});await page.goto('/playground/');await expect(page.locator('#play-status')).toContainText('4 result rows');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Inspect',exact:true}).click();await expect(page.locator('#inspector-panel')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('#inspector-toggle')).toBeFocused();await page.screenshot({path:'artifacts/site-browser/playground-mobile.png',fullPage:true});expect(errors).toEqual([]);});
test('every catalog route mounts its actual component and content remains readable without scripts',async({page,browser})=>{
 const catalog=(await import('../../harness/components.json',{with:{type:'json'}})).default.components;const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
 for(const component of catalog){await page.goto(`/docs/components/${component.id}/`);const id=component.id.slice(component.id.indexOf('.')+1);await expect(page.locator(`[data-component-preview] aeliqo-${id}`).first()).toBeAttached();await expect(page.locator('[data-component-preview]')).toContainText('Expected result');}
 expect(errors).toEqual([]);const context=await browser.newContext({javaScriptEnabled:false});const staticPage=await context.newPage();await staticPage.goto(new URL('/docs/concepts/',page.url()).href);await expect(staticPage.getByRole('heading',{name:'Four public concepts',exact:true})).toBeVisible();await context.close();const response=await page.goto('/missing-page/');expect(response?.status()).toBe(404);await expect(page.getByRole('heading',{name:'Page not found',exact:true})).toBeVisible();
});
