import {expect, test} from '@playwright/test';

test('task chooser, inspector summaries, and actionable recovery form a complete people journey', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/playground/');
  await expect(page.locator('#play-status')).toContainText('4 result rows');
  await expect(page.locator('#workflow-meter')).toHaveAttribute('value', '1');
  await page.locator('#task-choice').selectOption('people-rank');
  await page.getByRole('button', {name: 'Run task'}).click();
  await expect(page.getByRole('alert')).toContainText('Define absence days');
  await page.getByRole('button', {name: 'Define absence days', exact: true}).click();
  await expect(page.locator('#workflow-progress')).toContainText('Absence-days meaning defined');
  await page.getByRole('button', {name: 'Freeze current people', exact: true}).click();
  await page.locator('#task-choice').selectOption('people-trend');
  await page.getByRole('button', {name: 'Run task'}).click();
  await expect(page.locator('aeliqo-trend')).toBeVisible();
  await expect(page.locator('#workflow-meter')).toHaveAttribute('value', '4');
  await page.getByRole('button', {name: 'Inspect', exact: true}).click();
  await page.locator('#inspector-tab').selectOption('Data');
  await expect(page.locator('#inspector-content')).toContainText('scopeDigest');
  await expect(page.locator('#inspector-content')).toContainText('rowCount');
  await expect(page.locator('#inspector-content')).not.toContainText('Ada Chen');
  await page.locator('#inspector-resize').focus();
  await page.keyboard.press('End');
  await expect(page.locator('#inspector-resize')).toHaveAttribute('aria-valuetext', '520 pixels');
  await page.getByRole('button', {name: 'Source', exact: true}).click();
  const sourceHandle = page.locator('#source-resize');
  const sourceBox = await sourceHandle.boundingBox();
  if (!sourceBox) throw Error('source resize handle is not visible');
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + 80);
  await page.mouse.down();
  await page.mouse.move(sourceBox.x + 48, sourceBox.y + 80, {steps: 3});
  await page.mouse.up();
  expect(Number(await sourceHandle.getAttribute('aria-valuenow'))).toBeGreaterThan(320);
  const download = page.waitForEvent('download');
  await page.getByRole('button', {name: 'Export Task + presentation'}).click();
  expect((await download).suggestedFilename()).toBe('aeliqo-playground.json');
  await page.locator('#task-choice').selectOption('people-periods');
  await page.evaluate(() => {
    (document.querySelector('#run-task') as HTMLButtonElement).click();
    (document.querySelector('#cancel') as HTMLButtonElement).click();
  });
  await expect(page.locator('#play-status')).toContainText('cancelled');
  await expect(page.locator('aeliqo-region')).toBeVisible();
  expect(errors).toEqual([]);
});

test('source records, guarded reset, commerce progress, and narrow drawers remain usable', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width: 360, height: 800});
  await page.goto('/playground/');
  await page.getByRole('button', {name: 'Source', exact: true}).click();
  await expect(page.locator('#source-panel')).toHaveAttribute('aria-modal', 'true');
  await page.locator('#source-section').selectOption('dataset');
  await expect(page.locator('#source-content')).toContainText('People & absence');
  await page.keyboard.press('Escape');
  await expect(page.locator('#source-toggle')).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator('#dataset').selectOption('products');
  await expect(page.locator('#commerce-progress')).toContainText('Step 2 of 3');
  await page.getByRole('textbox', {name: 'Your name', exact: true}).fill('Nino');
  await page.getByRole('button', {name: 'Review local enquiry'}).click();
  await expect(page.locator('#commerce-progress')).toContainText('Step 3 of 3');
  await page.getByRole('button', {name: 'Source', exact: true}).click();
  await page.locator('#source-section').selectOption('task');
  await page.locator('#task-draft').fill('{"local":"draft"}');
  page.once('dialog', async dialog => {
    expect(dialog.message()).toContain('discard your local drafts');
    await dialog.dismiss();
  });
  await page.getByRole('button', {name: 'Reset session'}).click();
  await expect(page.locator('#dataset')).toHaveValue('products');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', {name: 'Reset session'}).click();
  await expect(page.locator('#dataset')).toHaveValue('employees');
  await expect(page.locator('#play-status')).toContainText('4 result rows');
  expect(errors).toEqual([]);
});
